apiVersion: v1
kind: Pod
metadata:
  name: "dbpod1"

spec: 
  containers:
  - name: "singdb"
    image: "mysql"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Singh@123"
    - name: MYSQL_DATABASE
      value: "Sunder"
    - name: MYSQL_USER_NAME
      value: "Sunder Singh"
    - name: MYSQL_PASSWORD
      value: "Sunder@123"